import { configureStore } from "@reduxjs/toolkit";
import counterReducer from './slices'
import { pokemonApi } from "../services/api";
import { setupListeners } from "@reduxjs/toolkit/query";

export const store = configureStore({
  reducer: {
    // pokemon autogenerated reducer as a specific top level slice
    [pokemonApi.reducerPath]: pokemonApi.reducer,
    counter: counterReducer
  },
  // adding api middleware enables caching, invalidation, polling
  // and other useful features from `rtk-query`
  middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(pokemonApi.middleware)

})

setupListeners(store.dispatch)